---
name: MapImageEngine
main: FaigerSYS\MapImageEngine\MapImageEngine
version: 2.0.0
api:
- 3.21.0
load: POSTWORLD
author: FaigerSYS
description: Image engine for MC:BE servers
permissions:
  mapimageengine:
    default: op
    description: Allows command usage (/mapimageengine)
...
